
GET  http://localhost:8080/ HTTP/1.1

###
POST http://localhost:8080/products HTTP/1.1
content-type: application/json

[
    {
        "_id": "639c19c57013b49915666d55",
        "image": "https://i.ibb.co/rxzqPWN/product-4.png",
        "price": "16.54",
        "qty": 1,
        "productName": "BCAA pro"
    },
    {
        "_id": "639c19c57013b49915666d54",
        "image": "https://i.ibb.co/pQFBWGb/product-3.png",
        "price": "16.54",
        "qty": 1,
        "productName": "100% WHEY"
    },
    {
        "_id": "639c19c57013b49915666d57",
        "image": "https://i.ibb.co/1bqh7Yx/product-5.png",
        "price": "16.54",
        "qty": 1,
        "productName": "ESSENTIALS"
    },
    {
        "_id": "639c19c57013b49915666d61",
        "image": "https://i.ibb.co/rxzqPWN/product-4.png",
        "price": "16.54",
        "qty": 1,
        "productName": "BCAA pro"
    },
    {
        "_id": "639c19c57013b49915666d5c",
        "image": "https://i.ibb.co/xqGSNGC/product-10.png",
        "price": "16.54",
        "qty": 1,
        "productName": "JUMPING ROPE"
    },
    {
        "_id": "639c19c57013b49915666d5a",
        "image": "https://i.ibb.co/mT0N794/product-8.png",
        "price": "16.54",
        "qty": 1,
        "productName": "HYDRA FUSION"
    },
    {
        "_id": "639c19c57013b49915666d68",
        "image": "https://i.ibb.co/xqGSNGC/product-10.png",
        "price": "16.54",
        "qty": 1,
        "productName": "JUMPING ROPE"
    },
    {
        "_id": "639c19c57013b49915666d58",
        "image": "https://i.ibb.co/BfPJ2HF/product-6.png",
        "price": "16.54",
        "qty": 1,
        "productName": "FLYING NINJA "
    },
    {
        "_id": "639c19c57013b49915666d5b",
        "image": "https://i.ibb.co/xqGSNGC/product-10.png",
        "price": "16.54",
        "qty": 1,
        "productName": "INVICTA DUMBBELL"
    },
    {
        "_id": "639c19c57013b49915666d69",
        "image": "https://i.ibb.co/123fSm3/product-11.png",
        "price": "16.54",
        "qty": 1,
        "productName": "Leather Lyca"
    },
    {
        "_id": "639c19c57013b49915666d5d",
        "image": "https://i.ibb.co/123fSm3/product-11.png",
        "price": "16.54",
        "qty": 1,
        "productName": "Leather Lyca"
    },
    {
        "_id": "639c19c57013b49915666d64",
        "image": "https://i.ibb.co/BfPJ2HF/product-6.png",
        "price": "16.54",
        "qty": 1,
        "productName": "FLYING NINJA "
    },
    {
        "_id": "639c19c57013b49915666d59",
        "image": "https://i.ibb.co/RQfmgyQ/product-7.png",
        "price": "16.54",
        "qty": 1,
        "productName": "HIGH POWER"
    },
    {
        "_id": "639c19c57013b49915666d53",
        "image": "https://i.ibb.co/94BnTpt/product-2.png",
        "price": "16.54",
        "qty": 1,
        "productName": "Winner Whey"
    },
    {
        "_id": "639c19c57013b49915666d56",
        "image": "https://i.ibb.co/rxzqPWN/product-4.png",
        "price": "16.54",
        "qty": 1,
        "productName": "DYNAMIC BCAA"
    },
    {
        "_id": "639c19c57013b49915666d63",
        "image": "https://i.ibb.co/1bqh7Yx/product-5.png",
        "price": "16.54",
        "qty": 1,
        "productName": "ESSENTIALS"
    },
    {
        "_id": "639c19c57013b49915666d6a",
        "image": "https://i.ibb.co/hMf5TJq/product-12.png",
        "price": "16.54",
        "qty": 1,
        "productName": "Mass Gainer"
    },
    {
        "_id": "639c1bc0f39964668c6eff3f",
        "productName": "100% WHEY",
        "image": "https://i.ibb.co/pQFBWGb/product-3.png",
        "price": "16.54",
        "qty": 1
    },
    {
        "_id": "639c19c57013b49915666d65",
        "image": "https://i.ibb.co/RQfmgyQ/product-7.png",
        "price": "16.54",
        "qty": 1,
        "productName": "HIGH POWER"
    },
    {
        "_id": "639c19c57013b49915666d60",
        "image": "https://i.ibb.co/pQFBWGb/product-3.png",
        "price": "16.54",
        "qty": 1,
        "productName": "100% WHEY"
    },
    {
        "_id": "639c1b676990e1e92e57a04c",
        "productName": "Winner xyz",
        "image": "https://i.ibb.co/94BnTpt/product-2.png",
        "price": "16.54",
        "qty": 1
    },
    {
        "_id": "639c1c3a22c84d41319ec7b5",
        "productName": "100% WHEY",
        "image": "https://i.ibb.co/pQFBWGb/product-3.png",
        "price": "16.54",
        "qty": 1
    },
    {
        "_id": "63a08b761a4d8509953ed5fb",
        "productName": "New Product ",
        "image": "https://i.ibb.co/1bqh7Yx/product-5.png",
        "price": "176",
        "qty": 1
    },
    {
        "_id": "63a15db44120b19377539236",
        "productName": "NEW PRODUCT ",
        "image": "https://i.ibb.co/1bqh7Yx/product-5.png",
        "price": "205",
        "qty": 1
    },
    {
        "_id": "63a165864120b193775392f3",
        "productName": "NEW PRODUCT ",
        "image": "https://i.ibb.co/1bqh7Yx/product-5.png",
        "price": "205",
        "qty": 1
    },
    {
        "_id": "6491db40d7e1e52bac8da4fd",
        "productName": "New protien ",
        "image": "https://gymbro.vercel.app/static/media/img1.95d4c1e73c1d019ff4d6.png",
        "price": "500",
        "qty": 1
    },
    {
        "_id": "6492715e338b08959291cff6",
        "productName": "Protein ",
        "image": "https://i.ibb.co/mT0N794/product-8.png",
        "price": "300",
        "qty": 1
    }
]